FROM python
RUN pip install flask
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  projectflask.py /home/myapp/
EXPOSE 5050
CMD python3 /home/myapp/projectflask.py
FROM python
COPY ./requirements.txt /home/myapp/
RUN pip install -r /home/myapp/requirements.txt
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  projectflask.py /home/myapp/
EXPOSE 5050
CMD python /home/myapp/projectflask.py
FROM python
COPY ./requirements.txt /home/myapp/
RUN pip install -r /home/myapp/requirements.txt
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  projectflask.py /home/myapp/
EXPOSE 5050
CMD python /home/myapp/projectflask.py
FROM python
COPY ./requirements.txt /home/myapp/
RUN pip install -r /home/myapp/requirements.txt
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  projectflask.py /home/myapp/
EXPOSE 5050
CMD python /home/myapp/projectflask.py
FROM python
COPY ./requirements.txt /home/myapp/
RUN pip install -r /home/myapp/requirements.txt
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  projectflask.py /home/myapp/
EXPOSE 5050
CMD python /home/myapp/projectflask.py
FROM python
COPY ./requirements.txt /home/myapp/
RUN pip install -r /home/myapp/requirements.txt
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  projectflask.py /home/myapp/
EXPOSE 5050
CMD python /home/myapp/projectflask.py
FROM python
COPY ./requirements.txt /home/myapp/
RUN pip install -r /home/myapp/requirements.txt
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  projectflask.py /home/myapp/
EXPOSE 5050
CMD python /home/myapp/projectflask.py
